name: Quality Assurance

# Ausfürhung bei Pull-Request auf main 
on: [pull_request]

jobs: 
 code_quality:
  name: Codequalitaet
  runs-on: ubuntu-latest
  
  steps:
   - name: ReproCheck
     uses: actions/ceckout@v2
     
     #andere Version 
   - name: Setup Node.js
     uses: action/setup-node@v2
     with: 
      node-version: 14 
     
     #Code Formatierung überprüfen
   - name: Codeformatierungscheck 
     run: npm run format:check
     
     #Überprüfung auf unsaubere Codestruktur, Stilabweichung, usw..
   - name: Linter 
     run: npm run lint 
     
     #Überprüft Code auf Duplikate
   - name: Codeduplikate Check
     run: npm run duplicates:check
     
     #Security Check, eig nicht benötigt 
   - name: SecCheck
     run: npm run security-scan
     
     #statsische Codeanalyse 
   - name: CodeAnalyse
     run: npm run code-analysis
     
     #eig gleich wie oben ?
   - name: statischeAna
     run: npm run static-analysis 
     
     #Audit
   - name: Audit
     run: npm audit
     
     #Codekomplexität
   - name: Codekomlexi
     run: npm run complexity-check 
     #
     
     
     


 

 
