name: Quality Assurance
on: push
jobs:
  code_quality:
    name: Codequalitaet
    runs-on: ubuntu-latest
    steps:
      - name: Codeformatierungscheck
        run: npm run format:check
      - name: Linter
        run: npm run lint
      - name: Codeduplikate Check
        run: npm run duplicates:check
      - name: SecCheck
        run: npm run security-scan
      - name: CodeAnalyse
        run: npm run code-analysis
      - name: statischeAna
        run: npm run static-analysis
      - name: Audit
        run: npm audit
      - name: Codekomlexi
        run: npm run complexity-check
